version: "3"
services:
  app:
    build: .
    container_name: nos-news-tracker-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      PGDATA: /pgsql/data
    volumes:
      - ./pgsql:/pgsql/data
    ports:
      - "5432:5432"
    restart: unless-stopped